# default configuration
baseURL = "https://sandip2224.netlify.app"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Sandipan ©"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about"
name = "About"
weight = 1

[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2

[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3

[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4


# default parameters
[params]
home = "Home"
logo = ""
# theme color
theme_color = "#41228e"
# contact info
phone = "+91 8918 777 740"
email = "sandipan2224@gmail.com"
address = "Siliguri, West Bengal, IN"
# meta description
author = "Sandipan Das"
description = "This is meta description"
# google analytics
google_analytics_id = "" # Your ID
# copyright
copyright = "Copyright &copy; 2021 by [sandip2224](https://github.com/sandip2224)"


# preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = true
form_action = "https://formsubmit.co/sandipan2224@gmail.com" # contact form works with : https://formspree.io

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=&#038;types=(cities)&#038;libraries=places&#038;language=en"
map_latitude = "26.727100"
map_longitude = "88.395287"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/sandipan_2224"

[[params.social]]
icon = "ti-linkedin"
URL = "https://www.linkedin.com/in/sandipan0164/"

[[params.social]]
icon = "ti-instagram"
URL = "https://www.instagram.com/sandipan_2224/"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/sandip2224"